# 使用外部数据库的配置（如果 MySQL 容器有问题）

services:
  redis:
    image: redis:7-alpine
    container_name: recruitment-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "46379:6379"
    networks:
      - recruitment-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitment-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      # 使用外部数据库
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-3306}
      REDIS_HOST: redis
    ports:
      - "45000:5000"
    depends_on:
      - redis
    networks:
      - recruitment-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:45000/api}
        REACT_APP_ALLOWED_EMAIL_DOMAIN: ${ALLOWED_EMAIL_DOMAIN:-@stu.example.edu.cn}
    container_name: recruitment-frontend
    restart: unless-stopped
    ports:
      - "43000:80"
    depends_on:
      - backend
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge

volumes:
  redis_data: